//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaners.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cleaner
    {
        public Cleaner()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s\-]*$", ErrorMessage ="Please us an initial capital letter")]
        public string Name { get; set; }

        public string Address { get; set; }

        public string City { get; set; }

        public string Postcode { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 10)]
        public string Phone { get; set; }

        [Required]
        [Range(0,1000)]
        [DataType(DataType.Currency)]
        [Display(Name ="Rate per Hour")]
        public decimal Rate { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
