//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaners.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Customer

    {
        public int Id { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 2)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s\-]*$", ErrorMessage = "Please us an initial capital letter")]
        public string Name { get; set; }

        public string Address { get; set; }

        public string City { get; set; }

        public string Postcode { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 10)]
        public string Phone { get; set; }

        [Required]
        public string Service { get; set; }

        [Required]
        [Display(Name = "Day")]
        public string CleaningDay { get; set; }

        [Required]
        [Display(Name = "Start")]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.TimeSpan> StartingHour { get; set; }

        [Required]
        [Display(Name = "Time")]
        public Nullable<decimal> Hours { get; set; }

        [Required]
        [Range(0, 1000)]
        [DataType(DataType.Currency)]
        public Nullable<decimal> Rate { get; set; }

        [Required]
        [Display(Name = "Cleaner")]
        public string CleanerName { get; set; }

        public int CleanerId { get; set; }

        public bool Checked;

        
        public string getEndHour (TimeSpan start, decimal time){

            TimeSpan timespan = TimeSpan.FromHours(Convert.ToDouble(time));
            TimeSpan endHour = start.Add(timespan);
            return endHour.ToString(@"hh\:mm");
        }
    
        public virtual Cleaner Cleaner { get; set; }
    }
}
